### ISSUE TITLE
Request for an advanced tutorial 5b about OF parallel computations

### ISSUE THREAD

**Issue by klausbu** [UnnamedMoose/BasicOpenFOAMProgrammingTutorials#17]
Hello Artur,

this is a request for an additional tutorial diving deeper into parallel computations.  It's a bid related to your comment in tutorial 5 "// Custom reduction operations are easy to implement but need fluency in    // object-oriented programming in OpenFOAM, so we'll skip this for now."
    
What I want to gain from such a tutorial is an idea about how to link/integrate computations of n specific processes (NOT ALL THE PROCESSES) which are offloaded to n GPUs?

It's really about the integration with the OF standard functionality, not about how offloading computations to the GPU works.  E.g. if there are 4 CPU MPI processes, CPU processes p0 (master), p1, p2, p3 where p2 <-> offloads computations to GPU0 and p3 <-> offloads computations to GPU1. Relevant operations are processor interface updates after mv multiplications and global communications when computing the norm, alpha and beta depending on relevant BLAS operations.

Thanks for your tutorials!

Klaus

**Comment by UnnamedMoose** [comment]
Hi Klaus,

I've looked into this briefly and the more I do the more it seems to be way too advanced and specific for these tutorials. The idea here is to teach people the very basics of MPI and not get into hybrid infrastructures and very much hardware-related issues. I'm therefore going to close this issue, sorry. Your question would be a much better fit for the cfd-online forum.

Kind regards,

A
