### ISSUE TITLE
new simple solver code to tutorials collection

### ISSUE THREAD

**Issue by Ramkumar47** [UnnamedMoose/BasicOpenFOAMProgrammingTutorials#19]
Hi, 
first of all.. its an excellent job from u.. it helped me a lot to learn OpenFOAM C++.. i am also like u, a self-taught person..
by the way, using the knowledge gained from ur tutorials, i have created a simple solver code, that solves wave equation.
i felt like it would be much useful for new coders and would like to add it to ur collection.. 
is it possible to do so?

**Comment by UnnamedMoose** [comment]
Hi Ramkumar, thanks a lot for the positive feedback, always great to hear about the tutorials making a difference. Of course, that sounds like a very cool addition to the collection. Please send me a pull request, I'll review it and merge with the main repo, adding you to the contributors list in the README.

**Comment by Ramkumar47** [comment]
Hi,
i have created the pull request, please check it, modify/edit if needed and if u find it to be worthy enough, then please add it to the tutorials list.

**Comment by UnnamedMoose** [comment]
Hey, that's great, many thanks! I'll look this over over the coming week.

**Comment by Ramkumar47** [comment]
i am working on a tutorial on solving ODE using OpenFOAM.. i will soon post a pull request for it ..

**Comment by UnnamedMoose** [comment]
Awesome, many thanks! Sorry to say this but I ran into some issues on my end, namely my laptop is of little more use than a brick and I only have Windows on the work one, so it'll take me a while to get to your pull request. Just know that it's very high up my priority list and I very much appreciate your contributions! Feel free to keep them coming :)

**Comment by UnnamedMoose** [comment]
Many apologies for being so slow on replying to this.... However, I have finally clawed away a bit of time to get on with merging your tutorial and I have to say, it's really nice! Many thanks for contributing it, it'll make a very good addition to the set already on there. I have merged the code already and will add it to the master branch soon. If you could please let me know what name you want to use in the acknowledgements section, that would allow me to give you credit properly. Thanks!

**Comment by Ramkumar47** [comment]
Hi, No problem because we all are busy with our stuff in this pandemic situation. I am very happy to hear that you liked the code and merged it.. By the way, in the acknowledgements section, you could use my real name "Ramkumar".  Thanks a lot!

**Comment by UnnamedMoose** [comment]
Done!

**Comment by Ramkumar47** [comment]
Thank you!.. i feel happy to be a part of the **contributors** list of git repo, which helped me a lot.. i will prepare more tutorials in future and put pull-requests for u !

**Comment by UnnamedMoose** [comment]
Always welcome :)

**Comment by Ramkumar47** [comment]
Hi,
 hope u have received a notification about new pull request i made.. it is a new tutorial that explains on matrix operations and solution to governing equations.. i took SIMPLE algorithm as an example and made this tutorial..
hope u find it to be worthy to add it to ur collections.
