### ISSUE TITLE
guidance for custom interpolation function

### ISSUE THREAD

**Issue by Ramkumar47** [UnnamedMoose/BasicOpenFOAMProgrammingTutorials#25]
Hi Artur!
I am ur fan Ramkumar, hope u remember me. 
I am on a new tutorial now and for that i need some guidance on compiling a custom interpolation function that i can use on fvSchemes file. could u plz guide me to a simple example or a set of instructions on compiling one?.. a simple example will do and i believe i can build up on that..  and u know to whom i am making the tutorial for :) ... could u plz guide me on this?

**Comment by UnnamedMoose** [comment]
Hey Ramkumar,

Sure, I remember you. I have never looked into discretisation in OF but I
agree that it'd be a very good addition to the tutorials. Any particular
scheme you're after? That would help me figure out what to focus on.

Thanks,

a

**Comment by Ramkumar47** [comment]
any simple scheme will do, like linear interpolation.. my need is to customize the linear interpolation scheme which seems to be a matching one.. i need instructions on how to compile a new scheme.. i cant find it anywhere..

**Comment by UnnamedMoose** [comment]
Hi Ramkumar,

Sorry it's been taking me a while, but I've opened a new branch and started
working on the new tutorial. I have a test case ready, now just need to add
the new code and test it.

Cheers,

A

**Comment by UnnamedMoose** [comment]
Hi again,

Sorry for being so slow on this, but I finally finished the new tutorial.
It turned out to be a lot more involved because I had never looked into
this aspect of the code before, but I'm glad you've asked for this as it
meant me having to brush off some of the fundamentals and learn a thing or
two! Happy to hear your feedback and amend things if needed.

Cheers,

A

**Comment by Ramkumar47** [comment]
Hi, i took a quick glance at ur work.. its excellent!!... and the great things like this will take time to come, so dont be sorry for being slow on this!... i will understand this in deep and implement it in my work... Thanks a lot!!.. 
and soon using this knowledge i will make tutorials, which i am having in my mind for a while and make a pull request..

Thank you again for spending ur valuable time on this... i dont know if u are on Facebook, there the OpenFOAM community finds this repo to be , and being shared very often..

**Comment by UnnamedMoose** [comment]
Hi,

Glad to hear it! I am not on facebook, no, but it's also good to hear that
people there are finding the tutorials useful.

Good luck & talk to you soon, I'm sure.

A
