### ISSUE TITLE
OFtutorial12_momentumSource 

### ISSUE THREAD

**Issue by Ethan-Gunnell** [UnnamedMoose/BasicOpenFOAMProgrammingTutorials#30]
An error is produced for OpenFOAM v2106 as follows: 

customActuationDiskSource.H:73:10: fatal error: fvModel.H: No such file or directory
   73 | #include "fvModel.H"

An error is produced for OpenFOAM 9 : 
 wmakeLnInclude error: base directory /opt/openfoam9/src/fvOptions/ does not exist

I'm not sure how I can get this tutorial to compile. I have added fvModel.H directly into the directory, but then it needs fvModelM.H. I feel like it should be able to find this header file but just isn't?

**Comment by UnnamedMoose** [comment]
Hi Ethan,

It seems that you're using a different OpenFOAM version - the tutorials are only compatible with this one: https://openfoam.org/version/9/ . This is also mentioned in the README.

The openfoam.org version may be easily installed alongside your existing version and you may switch between them by adjusting your .bashrc as needed. I'm sorry, but making the code compatible with all the popular OpenFOAM source trees would require way more time than I can spare right now.

Good luck,

A
