### ISSUE TITLE
Typo in tutorial 4 line 113

### ISSUE THREAD

**Issue by s1291** [UnnamedMoose/BasicOpenFOAMProgrammingTutorials#9]
In the tutorial 4, line 113: 
```
112         // In Python, this is equivalent to:
113         // np.sqrt(np.sum(x0-x)**2)
```
There is a typo in the comment, because the python expression computes the square root of the square of the sum that is the sum itself. Instead, we should calculate the square root of the sum of squares, it must changed to:
`113         // np.sqrt(np.sum((x0-x)**2)) << by adding paraenthesis inside sum function`

**Comment by UnnamedMoose** [comment]
Thanks for spotting it, fixed!
